"""create initial tables

Revision ID: 0ed064d629b8
Revises: 
Create Date: 2026-08-19 16:22:22.084878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed064d629b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produto',
    sa.Column('id_produto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_produto', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('status_pedido', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_frete', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('item_pedido',
    sa.Column('id_item_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item_pedido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedido')
    op.drop_table('pedido')
    op.drop_table('produto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
